/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utsr4bro;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SUPER USER
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bt2 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1Data = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        b1 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        d1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        d2 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utsr4bro/LogoUTS_1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 383, 470);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 380, 530);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));
        jPanel2.setLayout(null);

        bt2.setBackground(new java.awt.Color(51, 51, 51));
        bt2.setFont(new java.awt.Font("AbandoN", 0, 14)); // NOI18N
        bt2.setForeground(new java.awt.Color(255, 255, 255));
        bt2.setText("Clear");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jPanel2.add(bt2);
        bt2.setBounds(230, 290, 100, 40);

        bt1.setBackground(new java.awt.Color(51, 51, 51));
        bt1.setFont(new java.awt.Font("AbandoN", 0, 14)); // NOI18N
        bt1.setForeground(new java.awt.Color(255, 255, 255));
        bt1.setText("Save");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jPanel2.add(bt1);
        bt1.setBounds(120, 290, 100, 40);

        bt3.setBackground(new java.awt.Color(51, 51, 51));
        bt3.setFont(new java.awt.Font("AbandoN", 0, 14)); // NOI18N
        bt3.setForeground(new java.awt.Color(255, 255, 255));
        bt3.setText("Delete");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        jPanel2.add(bt3);
        bt3.setBounds(350, 290, 100, 40);

        bt5.setBackground(new java.awt.Color(51, 51, 51));
        bt5.setFont(new java.awt.Font("AbandoN", 0, 14)); // NOI18N
        bt5.setForeground(new java.awt.Color(255, 255, 255));
        bt5.setText("REFRESH");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        jPanel2.add(bt5);
        bt5.setBounds(460, 290, 100, 40);

        bt4.setBackground(new java.awt.Color(51, 51, 51));
        bt4.setFont(new java.awt.Font("AbandoN", 0, 14)); // NOI18N
        bt4.setForeground(new java.awt.Color(255, 255, 255));
        bt4.setText("Print");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        jPanel2.add(bt4);
        bt4.setBounds(570, 290, 100, 40);

        bt6.setBackground(new java.awt.Color(51, 51, 51));
        bt6.setFont(new java.awt.Font("AbandoN", 0, 14)); // NOI18N
        bt6.setForeground(new java.awt.Color(255, 255, 255));
        bt6.setText("EXIT");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        jPanel2.add(bt6);
        bt6.setBounds(680, 290, 100, 40);

        tb1Data.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        tb1Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Anggota", "Nama Peminjam", "Alamat Peminjam", "Judul Buku", "Status", "TanggalPinjam", "Tanggal Kembali", "Jenis"
            }
        ));
        tb1Data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1DataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1Data);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 340, 830, 110);

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Another America", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("No Anggota");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 50, 80, 40);

        t1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel2.add(t1);
        t1.setBounds(170, 50, 210, 40);

        t2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel2.add(t2);
        t2.setBounds(170, 100, 210, 40);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Another America", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nama Peminjam");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 100, 100, 40);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Another America", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Alamat Peminjam");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 150, 100, 40);

        t3.setColumns(20);
        t3.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        t3.setRows(5);
        jScrollPane2.setViewportView(t3);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(170, 150, 210, 130);

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Another America", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Judul Buku");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(450, 50, 80, 30);

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        jPanel2.add(t4);
        t4.setBounds(530, 50, 210, 33);

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Another America", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Status");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(450, 90, 80, 40);

        buttonGroup1.add(b1);
        b1.setFont(new java.awt.Font("Another America", 0, 24)); // NOI18N
        b1.setForeground(new java.awt.Color(51, 51, 51));
        b1.setText("Kembali");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel2.add(b1);
        b1.setBounds(530, 100, 110, 30);

        buttonGroup1.add(b2);
        b2.setFont(new java.awt.Font("Another America", 0, 24)); // NOI18N
        b2.setForeground(new java.awt.Color(51, 51, 51));
        b2.setText("Belum");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel2.add(b2);
        b2.setBounds(650, 100, 100, 30);

        d1.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jPanel2.add(d1);
        d1.setBounds(530, 150, 210, 30);

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Another America", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Tanggal Pinjam");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(420, 140, 120, 50);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Another America", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Tanggal Kembali");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(420, 180, 120, 50);
        jPanel2.add(d2);
        d2.setBounds(530, 190, 210, 30);

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Another America", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Jenis Buku");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(450, 240, 80, 30);

        c1.setFont(new java.awt.Font("Tall Films", 0, 24)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelajaran", "Komik", "Novel" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel2.add(c1);
        c1.setBounds(530, 240, 100, 30);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(40, 0, 1180, 510);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(330, 0, 980, 520);

        setBounds(0, 0, 1241, 506);
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalPinjam = dateFormat.format(d1.getDate());
        String tanggalKembali = dateFormat.format(d2.getDate());
        String jenis = (String)c1.getSelectedItem();
        if ("".equals(t1.getText()) || "".equals(t2.getText()) ||
            "".equals(t3.getText()) || "".equals(t4.getText())||tanggalPinjam.equals("")||tanggalKembali.equals("")||jenis.equals("")){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String JK="";

            if(b1.isSelected())
            JK = "Kembali";
            else
            JK = "Belum";

            String SQL = "INSERT INTO t_peminjam (NoAnggota,NamaPeminjam,AlamatPeminjam,JudulBuku,Status,TanggalPinjam,TanggalKembali,Jenis) "
            + "VALUES('"+t1.getText()+"','"+t2.getText()+"',"
            + "'"+t3.getText()+"','"+t4.getText()+"','"+JK+"','"+tanggalPinjam+"','"+tanggalKembali+"','"+jenis+"')";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void tb1DataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1DataMouseClicked
        int baris = tb1Data.getSelectedRow();
        if(baris != -1) {
            t1.setText(tb1Data.getValueAt(baris,0).toString());
            t2.setText(tb1Data.getValueAt(baris,1).toString());
            
            t3.setText(tb1Data.getValueAt(baris,2).toString());
            t4.setText(tb1Data.getValueAt(baris,3).toString());
            if("Kembali".equals(tb1Data.getValueAt(baris,4).toString())) {
                b1.setSelected(true);
            } else {
                b2.setSelected(true);
            }
                        
        }
    }//GEN-LAST:event_tb1DataMouseClicked

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        int baris = tb1Data.getSelectedRow();
        if(baris!=-1){
            String NoAnggota = tb1Data.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_peminjam WHERE NoAnggota='"+NoAnggota+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil terhapus","Sukses",JOptionPane.INFORMATION_MESSAGE);

            }else{
                JOptionPane.showMessageDialog(this, "Data gagal terhapus","Sukses",JOptionPane.WARNING_MESSAGE);

            }}
            else{
                JOptionPane.showMessageDialog(this,"Pilih Baris data terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        selectData();
    
    }//GEN-LAST:event_bt5ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        
    }//GEN-LAST:event_c1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        MessageFormat header = new MessageFormat("Daftar Spesifik Peminjam Perpustakaan ");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}    ");
        try{
            tb1Data.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
        
    }//GEN-LAST:event_bt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> c1;
    private com.toedter.calendar.JDateChooser d1;
    private com.toedter.calendar.JDateChooser d2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextArea t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTable tb1Data;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[]={"NoAnggota","NamaPeminjam","AlamatPeminjam","JudulBuku","Status","TanggalPinjam","TanggalKembali","Jenis"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL= "SELECT * FROM t_peminjam";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String NoAnggota = rs.getString(1);
                String NamaPeminjam = rs.getString(2);
                String Status = "";
                if("Kembali".equals(rs.getString(5))){
                    Status = "Kembali";
                }
                else{
                    Status = "Belum";
                }
                String AlamatPeminjam = rs.getString(3);
                String JudulBuku = rs.getString(4);
                String TanggalPinjam = rs.getString(6);
                String TanggalKembali = rs.getString(7);
                String Jenis = rs.getString(8);
               
                String data[]={NoAnggota,NamaPeminjam,AlamatPeminjam,JudulBuku,Status,TanggalPinjam,TanggalKembali,Jenis};
                dtm.addRow(data);
            }}
        catch (SQLException ex){
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE,null,ex);
                }
        tb1Data.setModel(dtm);
    }
}
